### ISSUE TITLE
Probabilities and cubic term

### ISSUE THREAD

**Issue by laurafdeza** [laurafdeza/Dissertation#11]
Hi @jgeller112,

These are the two questions:

1. I have a growth curve analysis in which I measure log odds of eye fixations on the target as a function of the fixed effects group (categorical), lexical stress (categorical), and pitch scores (aka pitch_dev, continuous). (In case it is of any help, the pitch scores refer to how fast participants perceived in what direction the pitch in a melody was changing. To get the pitch scores, I took time in ms, ran a glm with predictors base note and direction of the change, and calculated the random effects for each participant.) The probabilities for the GCA are in [the report](https://github.com/laurafdeza/Dissertation/blob/master/reports/music_report.Rmd) starting line 122. As you can see, the model has treated pitch scores as categorical. I checked in the dataset what class the pitch scores are considered and it said numeric. In the predictions, it also said numeric. I'm assuming that numeric in this case is synonym of continuous? The script with the model is [this one](https://github.com/laurafdeza/Dissertation/blob/master/scripts/music/analyses/03_analysis_gca.R). Maybe I've been looking to the script too much and I can't find the error anymore. Given pitch scores are continuous, there should not be that many probabilities for that fixed effect, right?

2. When interpreting the time terms in the GCA, I'm interpreting the first term as the steepness of the slope and the second term as the bowness, that is, when fixations on the target start to increase. I'm kind of lost about how to interpret the third term. All the examples I can find have either only first and second terms, or they do not really explain what the effect on the third term mean. Do you know of any resource that could help me with this? I've been using Mirman's book _Growth Curve Analysis and Visualization with R_ and a few articles I could find. I didn't find anything helpful in stack exchange so far either.

**Comment by jgeller112** [comment]
Quick answer to question 2

Within the context of GCA and VWP, interpretation is commonly limited to lower-level terms (intercept, linear, and quadratic). However, in order to accurately fit the data you should fit higher-level terms. Within GCA, the cubic polynomial allows the growth curve to be fit with two inflection points: the point when the looks to target start to increase from baseline and the point when the looks to target stops. In the VWP, the cubic term would gain a meaningful cognitive interpretation if participants tend to look to an object, then away, and then come back to it. I’m not sure there are really good examples of this in VWP. As you maybe know, the use of GCA for eye movement data is slowly being supplanted by other methods (GAMs , logistic and double Gaussian curves).  My suggestion is to limit interpretation to linear and quadratic terms as is suggested by Dan in book and papers, but make sure you use higher order terms to better fit the data.

**Comment by jgeller112** [comment]
@laurafdeza, answers to your questions below: 

 > In the predictions, it also said numeric. I'm assuming that numeric in this case is synonym of continuous?

Yes.

> I have a growth curve analysis in which I measure log odds of eye fixations on the target as a function of the fixed effects group (categorical), lexical stress (categorical), and pitch scores (aka pitch_dev, continuous). (In case it is of any help, the pitch scores refer to how fast participants perceived in what direction the pitch in a melody was changing. To get the pitch scores, I took time in ms, ran a glm with predictors base note and direction of the change, and calculated the random effects for each participant.) The probabilities for the GCA are in the report starting line 122. As you can see, the model has treated pitch scores as categorical. I checked in the dataset what class the pitch scores are considered and it said numeric

This is normal behavior. What it is doing is calculating the probability at each unique pitch score for each level of stress and group level. When you run the GCA the pitch variable is treated as continuous in the model. 

> 2. When interpreting the time terms in the GCA, I'm interpreting the first term as the steepness of the slope and the second term as the bowness, that is, when fixations on the target start to increase. I'm kind of lost about how to interpret the third term. All the examples I can find have either only first and second terms, or they do not really explain what the effect on the third term mean. Do you know of any resource that could help me with this? I've been using Mirman's book Growth Curve Analysis and Visualization with R and a few articles I could find. I didn't find anything helpful in stack exchange so far either.

Within the context of GCA and VWP, interpretation is commonly limited to lower-level terms (intercept, linear, and quadratic). However, in order to accurately fit the data you should fit higher-level terms. Within GCA, the cubic polynomial allows the growth curve to be fit with two inflection points: the point when the looks to target start to increase from baseline and the point when the looks to target stops. In the VWP, the cubic term would gain a meaningful cognitive interpretation if participants tend to look to an object, then away, and then come back to it. I’m not sure there are really good examples of this in VWP. As you maybe know, the use of GCA for eye movement data is slowly being supplanted by other methods (GAMs , logistic and double Gaussian curves). My suggestion is to limit interpretation to linear and quadratic terms as is suggested by Dan in book and papers, but make sure you use higher order terms to better fit the data.

I hope this answers your questions! Please let me know if I did not answer you adequately, or you have any more questions.

**Comment by laurafdeza** [comment]
Hi Jason,

Thank you very much. It did answer my questions! 

A follow-up question for the probabilties issues would be if there is any way to condense that information instead of having a different estimate for each pitch score.

Hope you enjoyed the break!

**Comment by jgeller112** [comment]
I hate to say this, but can you categorize pitch somehow (high vs. low?).

**Comment by laurafdeza** [comment]
I could, yes. But that would be for the probabilities only or for running the models too?

**Comment by jgeller112** [comment]
I am not sure what your research question(s) are. If you do not have specific hypotheses about particular values of pitch, but instead have broader hypotheses, then I say categorize them somehow.

**Comment by laurafdeza** [comment]
Ok. I'll try that. Thank you!
